# Usage: cmake -DIN_FILE=x.spv -DOUT_FILE=x.h -DVAR_NAME=kFoo -P EmbedSpirv.cmake
# Emits `inline constexpr uint32_t <VAR_NAME>[] = { ... };` plus a matching
# `<VAR_NAME>_size` (byte count) so callers can pass it straight to
# VkShaderModuleCreateInfo::pCode / codeSize without any runtime file I/O.
file(READ "${IN_FILE}" hex_content HEX)
string(LENGTH "${hex_content}" hex_len)
math(EXPR byte_count "${hex_len} / 2")

# SPIR-V words are 4-byte little-endian; group hex pairs into 8-hex-digit
# words matching VkShaderModuleCreateInfo's uint32_t* pCode expectation.
string(REGEX MATCHALL "................" words "${hex_content}")

set(out "// Auto-generated by EmbedSpirv.cmake from ${IN_FILE}. Do not edit.\n")
string(APPEND out "#pragma once\n#include <cstdint>\n#include <cstddef>\n\n")
string(APPEND out "inline constexpr uint32_t ${VAR_NAME}[] = {\n")
foreach(w ${words})
    # Reverse byte order (file is little-endian bytes, we read big-endian hex
    # pairs left-to-right) so the emitted uint32_t literal matches the
    # in-memory little-endian word SPIR-V expects.
    string(SUBSTRING "${w}" 0 2 b0)
    string(SUBSTRING "${w}" 2 2 b1)
    string(SUBSTRING "${w}" 4 2 b2)
    string(SUBSTRING "${w}" 6 2 b3)
    string(APPEND out "0x${b3}${b2}${b1}${b0},")
endforeach()
string(APPEND out "\n};\n")
string(APPEND out "inline constexpr size_t ${VAR_NAME}_size = sizeof(${VAR_NAME});\n")

file(WRITE "${OUT_FILE}" "${out}")
